version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.0
    container_name: broker
    hostname: broker
    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:
      # ===== KRaft single-node =====
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # ===== LISTENERS (ОДНОЙ СТРОКОЙ!) =====
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://broker:9093

      # ===== ADVERTISED (ТОЛЬКО клиентский) =====
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # ===== PROTOCOL MAP =====
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      # ===== CONTROLLER =====
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093

      # ===== INTER-BROKER =====
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # ===== SINGLE NODE SAFETY =====
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      # ===== DEV =====
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  pg_data:
