# ЗАМЕНИТЕ ВСЕ /tmp/loki на /loki
auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki  # ИЗМЕНИТЕ!
  storage:
    filesystem:
      chunks_directory: /loki/chunks  # ИЗМЕНИТЕ!
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index  # ИЗМЕНИТЕ!
    cache_location: /loki/boltdb-shipper-cache  # ИЗМЕНИТЕ!
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks  # ИЗМЕНИТЕ!

compactor:
  working_directory: /loki/compactor  # ИЗМЕНИТЕ!
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

# ДОБАВЬТЕ ЭТУ СЕКЦИЮ ДЛЯ RULER!
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules  # или /loki/rules_storage
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093  # если не используете Alertmanager, можно оставить

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s